#label: Good Day
config.hello: Hello

spring:
  profiles: dev,cloud
#  cloud:
#    config:
#      watch:
#        enabled: true
#        delay: 5000
#        initialDelay: 5000

endpoints:
  health:
    sensitive: false

security:
  basic:
    enabled:  false

management:
  security:
    enabled: false